name: yCampo
version: '${project.version}'
main: com.ystoreplugins.ycampo.Main
authors: [ yChusy ]
website: https://ystoreplugins.com.br
depend: [ yPlugins ]
softdepend: [ HolographicDisplays, DecentHolograms, PlaceholderAPI ]
